name: ace3p
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  workflow_call:  # This allows this workflow to be called from another workflow
  
jobs:
  build-kernel-ace3p-kernelsu-susfs:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      model: "ace3p"
      soc: "pineapple"
      branch: "oneplus/sm8650"
      manifest: "oneplus_ace3_pro_v.xml"
      android_version: "android14"
      kernel_version: "6.1"
