name: Test Space

on:
  workflow_dispatch:  # This allows this workflow to be called from another workflow
  
jobs:
  test_build_space:
    runs-on: ubuntu-latest

    steps:
      - name: Get build space before
        run: |
          free -h
          df -h
    
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192    # 16GB for root memory reservation
          temp-reserve-mb: 2048     # 8GB for temporary memory reservation
          swap-size-mb: 8192       # 16GB for swap size
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Get build space after
        run: |
          free -h
          df -h
